#!/usr/bin/env bash
# make_pdr_index.sh — Generate 08_PDRS/PDR_INDEX.md
#
# Reconciles every PDR's *declared* status against the *live* state of the
# beads it references in `bd`, so we always know where each PDR sits in the
# Definition-of-Done lifecycle and which PDRs have drifted from their beads.
#
# Source of truth precedence (highest first):
#   1. ARCHIVE_COMPLETED/  -> stage = done (archived)
#   2. bd bead status      -> live work state (closed/in_progress/open/blocked)
#   3. PDR "**Status:**"   -> declared intent (draft/approved/...)
#
# A PDR is flagged when declared status and bead-derived status disagree, or
# when it references a bead id that does not exist in `bd`.
#
# Usage:  bash 08_PDRS/scripts/make_pdr_index.sh [--check]
#   (no args)  regenerate 08_PDRS/PDR_INDEX.md
#   --check    exit 1 if the index is stale or any PDR has a reconciliation
#              warning (suitable for a pre-commit / CI gate)
set -uo pipefail

PDR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INDEX="$PDR_DIR/PDR_INDEX.md"
ARCHIVE="$PDR_DIR/ARCHIVE_COMPLETED"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

have_bd=0
command -v bd >/dev/null 2>&1 && have_bd=1

# bead id -> live status word (open|in_progress|blocked|closed|MISSING)
bead_status() {
  local id="$1"
  [ "$have_bd" -eq 1 ] || { echo "unknown"; return; }
  local out
  out="$(bd show "$id" 2>/dev/null)" || { echo "MISSING"; return; }
  [ -z "$out" ] && { echo "MISSING"; return; }
  # bd show's header line ends with e.g. "[● P1 · IN_PROGRESS]"; read that token.
  printf '%s\n' "$out" | head -1 | grep -ioE '(in_progress|open|blocked|closed|deferred)' \
    | head -1 | tr 'A-Z' 'a-z' || echo "open"
}

# Derive a lifecycle stage from declared status + bead statuses.
derive_stage() {
  local declared="$1" beads_state="$2" archived="$3"
  [ "$archived" = "1" ] && { echo "done (archived)"; return; }
  case "$beads_state" in
    *closed*)        echo "done";;
    *in_progress*)   echo "in-progress";;
    *blocked*)       echo "blocked";;
    *MISSING*)       # no live bead — fall back to declared intent
      case "$declared" in
        *pproved*) echo "approved (no live bead)";;
        *) echo "draft (no live bead)";;
      esac;;
    *open*)          echo "approved";;
    *) # no beads parsed at all
      case "$declared" in
        *pproved*) echo "approved";;
        *) echo "draft";;
      esac;;
  esac
}

emit() {
  echo "# PDR Index — Chromatic Harness v2"
  echo
  echo "> Auto-generated by \`08_PDRS/scripts/make_pdr_index.sh\`. Do not edit by hand."
  echo "> Reconciles each PDR's declared **Status** against live \`bd\` bead state."
  echo "> Lifecycle (Definition of Done): CAPTURE → SPEC → PRE-MORTEM → TDD → VERIFY → HARDEN → LEAN → SHIP → LIVE → OBSERVE."
  echo
  if [ "$have_bd" -eq 0 ]; then
    echo "> ⚠️ \`bd\` not on PATH at generation time — bead columns are unverified."
    echo
  fi

  echo "## Active PDRs"
  echo
  echo "| PDR | Declared | Beads | Bead state | Derived stage | Flags |"
  echo "|-----|----------|-------|-----------|---------------|-------|"

  local warnings=0
  local f base declared beads beads_state stage flags id st
  for f in "$PDR_DIR"/*.md; do
    base="$(basename "$f")"
    case "$base" in PDR_INDEX.md|DEFINITION_OF_DONE.md|_PDR_TEMPLATE.md) continue;; esac

    declared="$(grep -m1 -iE '^\*\*Status:\*\*' "$f" | sed -E 's/^\*\*Status:\*\*[[:space:]]*//; s/[[:space:]]*·.*$//' )"
    [ -z "$declared" ] && declared="—"

    # Extract bead ids from a "**Beads:**" line: strip backticks, split on , and space
    beads="$(grep -m1 -iE 'Beads:' "$f" | sed -E 's/.*Beads:\**//I; s/·.*$//; s/`//g; s/[(][^)]*[)]//g' \
             | tr ',' ' ' | tr -s ' ' )"
    beads="$(echo "$beads" | xargs 2>/dev/null)"

    beads_state=""; flags=""
    local bead_cell="—"
    if [ -n "$beads" ]; then
      bead_cell=""
      for id in $beads; do
        case "$id" in -|—|TBD|tbd|'<bd-id>') continue;; esac
        st="$(bead_status "$id")"
        beads_state="$beads_state $st"
        bead_cell="$bead_cell\`$id\`=$st "
        if [ "$st" = "MISSING" ]; then
          flags="$flags ⚠️bead-missing"; warnings=$((warnings+1))
        fi
      done
      [ -z "$bead_cell" ] && bead_cell="—"
    else
      flags="$flags ⚠️no-bead"; warnings=$((warnings+1))
    fi

    local archived=0
    stage="$(derive_stage "$declared" "$beads_state" "$archived")"

    # disagreement: declared says draft but bead closed, or declared approved but no live bead
    case "$declared:$stage" in
      *draft*:done*|*draft*:in-progress*) flags="$flags ⚠️declared-stale";;
    esac

    printf '| %s | %s | %s | %s | %s | %s |\n' \
      "$base" "$declared" "$([ -n "$beads" ] && echo "$beads" || echo '—')" \
      "${bead_cell}" "$stage" "${flags:-ok}"
  done

  echo
  echo "## Archived / Completed PDRs"
  echo
  if [ -d "$ARCHIVE" ]; then
    echo "| PDR | Stage |"
    echo "|-----|-------|"
    for f in "$ARCHIVE"/*.md; do
      [ -e "$f" ] || continue
      printf '| %s | done (archived) |\n' "$(basename "$f")"
    done
  else
    echo "_No ARCHIVE_COMPLETED/ directory._"
  fi

  echo
  echo "## Reconciliation summary"
  echo
  echo "- Warnings (missing/no bead or declared-vs-live drift): **$warnings**"
  echo "- Generated against \`bd\` $([ "$have_bd" -eq 1 ] && bd --version 2>/dev/null | head -1 || echo '(unavailable)')"
  echo
  echo "_Regenerate with \`bash 08_PDRS/scripts/make_pdr_index.sh\`._"

  return $warnings
}

if [ "$CHECK" -eq 1 ]; then
  tmp="$(mktemp)"
  emit > "$tmp"; warn=$?
  if [ -f "$INDEX" ] && diff -q "$INDEX" "$tmp" >/dev/null 2>&1 && [ "$warn" -eq 0 ]; then
    rm -f "$tmp"; echo "PDR_INDEX.md is current and clean."; exit 0
  fi
  rm -f "$tmp"
  echo "PDR_INDEX.md is stale or has $warn reconciliation warning(s). Run make_pdr_index.sh." >&2
  exit 1
fi

emit > "$INDEX"
warn=$?
echo "Wrote $INDEX ($warn reconciliation warning(s))."
