// AUTO-GENERATED by scripts/generate_console_themes.py — DO NOT EDIT BY HAND.
// Source of truth: assets/prompt_variants/*.asset_pack.yaml
// (validated against schemas/asset_swap_pack.schema.json). Regenerate after editing a pack:
//   python scripts/generate_console_themes.py

export interface ConsoleTheme {
  id: string;
  name: string;
  style: string;
  bg: string;
  panelBg: string;
  panelBorder: string;
  heading: string;
  text: string;
  muted: string;
  accent: string;
  brand: string;
  success: string;
  warning: string;
  danger: string;
  info: string;
  palette: Record<string, string>;
  components: Record<string, string>;
}

export type ThemeId = "default_neon" | "magnetic_gold" | "prism_cosmic";

export const THEMES: ConsoleTheme[] = [
  {
    "id": "default_neon",
    "name": "Default Neon Command Center",
    "style": "dark neon operations console",
    "bg": "#0a0a0a",
    "panelBg": "#111111",
    "panelBorder": "#333333",
    "heading": "#888888",
    "text": "#e0e0e0",
    "muted": "#555555",
    "accent": "#3b82f6",
    "brand": "#8b5cf6",
    "success": "#22c55e",
    "warning": "#facc15",
    "danger": "#f97316",
    "info": "#3b82f6",
    "palette": {
      "cmp": "#8b5cf6",
      "runtime": "#3b82f6",
      "mcp": "#22c55e",
      "magnets": "#facc15",
      "beads": "#14b8a6",
      "risk": "#f97316"
    },
    "components": {
      "panels": "glass_neon",
      "gauges": "circular_glow",
      "graphs": "node_pipeline",
      "cards": "bordered_dark_cards"
    }
  },
  {
    "id": "magnetic_gold",
    "name": "Magnetic Gold Operations",
    "style": "black and gold magnet observability console",
    "bg": "#0a0a0a",
    "panelBg": "#111111",
    "panelBorder": "#333333",
    "heading": "#888888",
    "text": "#e0e0e0",
    "muted": "#555555",
    "accent": "#facc15",
    "brand": "#a855f7",
    "success": "#22c55e",
    "warning": "#f59e0b",
    "danger": "#ef4444",
    "info": "#facc15",
    "palette": {
      "primary": "#facc15",
      "secondary": "#a855f7",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "danger": "#ef4444"
    },
    "components": {
      "panels": "amber_holographic",
      "gauges": "gold_confidence_arc",
      "graphs": "magnet_inflection_chain",
      "cards": "observability_probe_cards"
    }
  },
  {
    "id": "prism_cosmic",
    "name": "Prism Cosmic Control",
    "style": "cosmic prism nebula control room",
    "bg": "#020617",
    "panelBg": "#111111",
    "panelBorder": "#333333",
    "heading": "#888888",
    "text": "#e0e0e0",
    "muted": "#555555",
    "accent": "#0ea5e9",
    "brand": "#c084fc",
    "success": "#22c55e",
    "warning": "#f59e0b",
    "danger": "#ec4899",
    "info": "#0ea5e9",
    "palette": {
      "prism": "#c084fc",
      "quasar": "#0ea5e9",
      "plasma": "#ec4899",
      "deep_space": "#020617"
    },
    "components": {
      "panels": "cosmic_glass",
      "gauges": "prism_ring",
      "graphs": "constellation_pipeline",
      "cards": "floating_hologram_cards"
    }
  }
];

export const DEFAULT_THEME_ID: ThemeId = "default_neon";

export function getTheme(id: string | null | undefined): ConsoleTheme {
  return THEMES.find((t) => t.id === id) ?? THEMES.find((t) => t.id === DEFAULT_THEME_ID) ?? THEMES[0];
}
