#!/usr/bin/env python3
"""auto_heal.py — Comprehensive self-healing script for Chromatic Harness V2.

Detects and repairs known broken harness states without modifying unrelated
code or governance artifacts. Each healer is independent and fail-safe.

Usage:
    python scripts/auto_heal.py               # detect and fix
    python scripts/auto_heal.py --check-only  # report without mutating

Exit codes:
    0 — all issues healed (or none found)
    1 — one or more issues remain unfixable
"""

from __future__ import annotations

import argparse
import datetime
import os
import sqlite3
import subprocess
import sys
import time
from pathlib import Path
from typing import Callable

# ── Paths ────────────────────────────────────────────────────────────────────

SCRIPTS = Path(__file__).resolve().parent
REPO = SCRIPTS.parent
LOGS_DIR = REPO / "07_LOGS_AND_AUDIT"
LOG_FILE = LOGS_DIR / "auto_heal.log"

# Python packages that must contain an __init__.py
REQUIRED_INIT_DIRS: list[Path] = [
    REPO / "02_RUNTIME",
    REPO / "scripts" / "kpi_collectors",
    REPO / "scripts" / "hooks",
]

# Required .gitignore entries (entry text → comment to add if missing)
REQUIRED_GITIGNORE: list[tuple[str, str]] = [
    ("*.pyc", "Compiled Python bytecode"),
    ("__pycache__/", "Python cache directories"),
    (".pytest_cache/", "Pytest cache"),
    ("*.log", "Log files"),
]

# ── ANSI colours (no external deps) ─────────────────────────────────────────

_USE_COLOR = sys.stdout.isatty() and os.environ.get("NO_COLOR") is None


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text


def green(t: str) -> str:
    return _c("32", t)


def yellow(t: str) -> str:
    return _c("33", t)


def red(t: str) -> str:
    return _c("31", t)


def cyan(t: str) -> str:
    return _c("36", t)


def bold(t: str) -> str:
    return _c("1", t)


# ── Logging ──────────────────────────────────────────────────────────────────

_log_lines: list[str] = []


def _ts() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _log(level: str, message: str) -> None:
    line = f"[{_ts()}] [{level:<5}] {message}"
    _log_lines.append(line)
    prefix = {"INFO": green("INFO"), "WARN": yellow("WARN"), "FIX": cyan("FIX "), "ERR": red("ERR ")}.get(
        level, level
    )
    print(f"  [{prefix}] {message}")


def _flush_log() -> None:
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    with LOG_FILE.open("a", encoding="utf-8") as fh:
        fh.write(f"\n--- auto_heal run {_ts()} ---\n")
        for line in _log_lines:
            fh.write(line + "\n")


# ── Result tracking ──────────────────────────────────────────────────────────


class HealResult:
    """Accumulates per-healer outcomes."""

    def __init__(self) -> None:
        self.fixed: list[str] = []
        self.skipped: list[str] = []      # check-only suppression
        self.unfixable: list[str] = []
        self.clean: list[str] = []

    @property
    def ok(self) -> bool:
        return not self.unfixable


# ── Individual healers ───────────────────────────────────────────────────────


def heal_missing_init_files(result: HealResult, check_only: bool) -> None:
    """Ensure every listed Python package directory has an __init__.py."""
    label = "missing-init"
    found_any = False

    for pkg_dir in REQUIRED_INIT_DIRS:
        if not pkg_dir.is_dir():
            _log("INFO", f"[{label}] skip — directory does not exist: {pkg_dir.relative_to(REPO)}")
            continue
        init_path = pkg_dir / "__init__.py"
        if init_path.exists():
            continue
        found_any = True
        rel = init_path.relative_to(REPO)
        if check_only:
            _log("WARN", f"[{label}] missing: {rel}")
            result.skipped.append(f"{label}: {rel}")
        else:
            try:
                init_path.write_text(
                    "# Auto-generated by auto_heal.py — marks this directory as a Python package.\n",
                    encoding="utf-8",
                )
                _log("FIX", f"[{label}] created {rel}")
                result.fixed.append(f"{label}: {rel}")
            except OSError as exc:
                _log("ERR", f"[{label}] cannot create {rel}: {exc}")
                result.unfixable.append(f"{label}: {rel} — {exc}")

    if not found_any:
        _log("INFO", f"[{label}] all __init__.py files present")
        result.clean.append(label)


def heal_broken_symlinks(result: HealResult, check_only: bool) -> None:
    """Remove dangling symlinks / junctions under the repo root.

    On Windows, Path.is_symlink() covers junction points created with
    mklink /J as well as regular symlinks, but the target check differs:
    junctions report is_dir()=True even when broken on some Python versions.
    We use lstat() to detect the link and os.path.exists() for reachability.
    """
    label = "broken-symlinks"
    found: list[Path] = []

    for path in REPO.rglob("*"):
        try:
            if path.is_symlink() and not path.exists():
                found.append(path)
        except (PermissionError, OSError):
            continue

    if not found:
        _log("INFO", f"[{label}] no broken symlinks found")
        result.clean.append(label)
        return

    for path in found:
        rel = path.relative_to(REPO)
        if check_only:
            _log("WARN", f"[{label}] broken symlink: {rel} -> {os.readlink(path)}")
            result.skipped.append(f"{label}: {rel}")
        else:
            try:
                path.unlink()
                _log("FIX", f"[{label}] removed broken symlink: {rel}")
                result.fixed.append(f"{label}: {rel}")
            except OSError as exc:
                _log("ERR", f"[{label}] cannot remove {rel}: {exc}")
                result.unfixable.append(f"{label}: {rel} — {exc}")


def heal_beads_state(result: HealResult, check_only: bool) -> None:  # noqa: ARG001
    """Verify .beads/db (SQLite) is readable; report if corrupted.

    This healer never deletes .beads data — corruption is unfixable here and
    must be escalated to the operator. We only test readability and integrity.
    """
    label = "beads-state"
    beads_dir = REPO / ".beads"
    db_path = beads_dir / "embeddeddolt" / "dolt" if (beads_dir / "embeddeddolt").is_dir() else beads_dir / "db"

    # Locate the actual sqlite file (.beads may store it at different sub-paths)
    candidates = [
        beads_dir / "embeddeddolt" / "dolt",
        beads_dir / "db",
        beads_dir / "data.db",
    ]
    db_file: Path | None = None
    for candidate in candidates:
        if candidate.is_file():
            db_file = candidate
            break

    if db_file is None:
        # .beads might not use SQLite at all — check for issues.jsonl instead
        jsonl = beads_dir / "issues.jsonl"
        if jsonl.is_file():
            try:
                bad = 0
                import json

                for line in jsonl.read_text(encoding="utf-8", errors="replace").splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        json.loads(line)
                    except json.JSONDecodeError:
                        bad += 1
                if bad:
                    _log("ERR", f"[{label}] {bad} corrupt line(s) in .beads/issues.jsonl — manual repair needed")
                    result.unfixable.append(f"{label}: {bad} corrupt jsonl lines")
                else:
                    _log("INFO", f"[{label}] .beads/issues.jsonl readable and intact")
                    result.clean.append(label)
            except OSError as exc:
                _log("ERR", f"[{label}] cannot read .beads/issues.jsonl: {exc}")
                result.unfixable.append(f"{label}: {exc}")
        elif not beads_dir.is_dir():
            _log("WARN", f"[{label}] .beads directory missing — beads not initialised")
            result.unfixable.append(f"{label}: .beads directory missing")
        else:
            _log("INFO", f"[{label}] .beads present but no SQLite DB located — skipping integrity check")
            result.clean.append(label)
        return

    # SQLite integrity check
    try:
        con = sqlite3.connect(str(db_file), timeout=5)
        cur = con.execute("PRAGMA integrity_check;")
        rows = cur.fetchall()
        con.close()
        if rows and rows[0][0] == "ok":
            _log("INFO", f"[{label}] SQLite integrity OK: {db_file.relative_to(REPO)}")
            result.clean.append(label)
        else:
            issues = [r[0] for r in rows]
            _log("ERR", f"[{label}] SQLite integrity FAIL: {issues[:5]} — manual repair needed")
            result.unfixable.append(f"{label}: integrity_check={issues[:3]}")
    except sqlite3.DatabaseError as exc:
        _log("ERR", f"[{label}] cannot open {db_file.relative_to(REPO)}: {exc} — file may be corrupted")
        result.unfixable.append(f"{label}: {exc}")
    except OSError as exc:
        _log("ERR", f"[{label}] OS error reading {db_file.relative_to(REPO)}: {exc}")
        result.unfixable.append(f"{label}: {exc}")


def heal_git_index_lock(result: HealResult, check_only: bool) -> None:
    """Remove stale .git/index.lock files (older than 60 seconds).

    A fresh lock (< 60 s) belongs to a live git process — we leave it alone.
    Locks older than 60 s are orphans left by a crashed process.
    """
    label = "git-index-lock"
    lock_path = REPO / ".git" / "index.lock"

    if not lock_path.exists():
        _log("INFO", f"[{label}] no index.lock present")
        result.clean.append(label)
        return

    age_s = time.time() - lock_path.stat().st_mtime
    if age_s < 60:
        _log("WARN", f"[{label}] index.lock is only {age_s:.0f}s old — git may be active, leaving it")
        result.skipped.append(f"{label}: lock age {age_s:.0f}s < 60s threshold (may be live)")
        return

    if check_only:
        _log("WARN", f"[{label}] stale index.lock ({age_s:.0f}s old) — would remove")
        result.skipped.append(f"{label}: stale lock {age_s:.0f}s old")
    else:
        try:
            lock_path.unlink()
            _log("FIX", f"[{label}] removed stale index.lock ({age_s:.0f}s old)")
            result.fixed.append(f"{label}: removed stale lock")
        except OSError as exc:
            _log("ERR", f"[{label}] cannot remove index.lock: {exc}")
            result.unfixable.append(f"{label}: {exc}")


def heal_gitignore_entries(result: HealResult, check_only: bool) -> None:
    """Ensure required patterns exist in .gitignore; append missing ones."""
    label = "gitignore"
    gitignore_path = REPO / ".gitignore"

    if not gitignore_path.is_file():
        _log("WARN", f"[{label}] .gitignore does not exist — creating it")
        if check_only:
            result.skipped.append(f"{label}: .gitignore missing")
            return
        try:
            gitignore_path.write_text("", encoding="utf-8")
        except OSError as exc:
            _log("ERR", f"[{label}] cannot create .gitignore: {exc}")
            result.unfixable.append(f"{label}: {exc}")
            return

    try:
        current_text = gitignore_path.read_text(encoding="utf-8")
    except OSError as exc:
        _log("ERR", f"[{label}] cannot read .gitignore: {exc}")
        result.unfixable.append(f"{label}: {exc}")
        return

    current_lines = set(current_text.splitlines())
    missing: list[tuple[str, str]] = []
    for pattern, comment in REQUIRED_GITIGNORE:
        if pattern not in current_lines:
            missing.append((pattern, comment))

    if not missing:
        _log("INFO", f"[{label}] all required .gitignore entries present")
        result.clean.append(label)
        return

    for pattern, comment in missing:
        _log("WARN", f"[{label}] missing pattern: {pattern}")

    if check_only:
        result.skipped.append(f"{label}: {len(missing)} missing pattern(s)")
        return

    try:
        additions = "\n# Added by auto_heal.py\n"
        for pattern, comment in missing:
            additions += f"# {comment}\n{pattern}\n"
        with gitignore_path.open("a", encoding="utf-8") as fh:
            fh.write(additions)
        _log("FIX", f"[{label}] appended {len(missing)} missing pattern(s) to .gitignore")
        result.fixed.append(f"{label}: appended {len(missing)} patterns")
    except OSError as exc:
        _log("ERR", f"[{label}] cannot append to .gitignore: {exc}")
        result.unfixable.append(f"{label}: {exc}")


def heal_orphaned_pyc(result: HealResult, check_only: bool) -> None:
    """Remove .pyc files whose corresponding .py source no longer exists.

    Only examines __pycache__ directories. Plain .pyc files adjacent to sources
    are also checked. We never touch .pyc files that have a live .py companion.
    """
    label = "orphaned-pyc"
    orphans: list[Path] = []

    # Scan __pycache__ dirs: file names are like module.cpython-311.pyc
    for pyc in REPO.rglob("__pycache__/*.pyc"):
        try:
            # Recover the original stem: strip .cpython-NNN or .pypy-NNN suffix
            stem = pyc.stem  # e.g. "module.cpython-311"
            # Split on the first dot-after-module-name that is followed by cpython/pypy
            parts = stem.split(".")
            module_name = parts[0]
            parent_src = pyc.parent.parent / f"{module_name}.py"
            if not parent_src.exists():
                orphans.append(pyc)
        except Exception:
            continue

    # Also scan top-level .pyc files (pre-Python-3.2 style)
    for pyc in REPO.rglob("*.pyc"):
        if "__pycache__" in pyc.parts:
            continue  # already handled above
        companion = pyc.with_suffix(".py")
        if not companion.exists():
            orphans.append(pyc)

    if not orphans:
        _log("INFO", f"[{label}] no orphaned .pyc files found")
        result.clean.append(label)
        return

    _log("WARN", f"[{label}] found {len(orphans)} orphaned .pyc file(s)")
    if check_only:
        for p in orphans[:10]:
            _log("WARN", f"[{label}]   {p.relative_to(REPO)}")
        if len(orphans) > 10:
            _log("WARN", f"[{label}]   … and {len(orphans) - 10} more")
        result.skipped.append(f"{label}: {len(orphans)} orphans")
        return

    removed = 0
    failed = 0
    for pyc in orphans:
        try:
            pyc.unlink()
            removed += 1
        except OSError as exc:
            _log("ERR", f"[{label}] cannot remove {pyc.relative_to(REPO)}: {exc}")
            failed += 1

    if removed:
        _log("FIX", f"[{label}] removed {removed} orphaned .pyc file(s)")
        result.fixed.append(f"{label}: removed {removed} .pyc files")
    if failed:
        result.unfixable.append(f"{label}: {failed} .pyc files could not be removed")


def heal_run_harness_health(result: HealResult, check_only: bool) -> None:  # noqa: ARG001
    """Invoke scripts/harness_health_check.py if it exists and surface failures."""
    label = "harness-health"
    health_script = SCRIPTS / "harness_health_check.py"

    if not health_script.is_file():
        _log("INFO", f"[{label}] harness_health_check.py not found — skipping")
        result.clean.append(label)
        return

    _log("INFO", f"[{label}] running harness_health_check.py …")
    try:
        proc = subprocess.run(
            [sys.executable, str(health_script)],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=30,
            cwd=str(REPO),
        )
    except subprocess.TimeoutExpired:
        _log("WARN", f"[{label}] harness_health_check.py timed out after 30s")
        result.unfixable.append(f"{label}: health check timed out")
        return
    except Exception as exc:
        _log("WARN", f"[{label}] could not run health check: {exc}")
        result.unfixable.append(f"{label}: {exc}")
        return

    if proc.returncode == 0:
        _log("INFO", f"[{label}] harness health: GREEN")
        result.clean.append(label)
    else:
        # Parse the JSON output for detail
        import json

        raw = (proc.stdout or "").strip()
        try:
            data = json.loads(raw)
            overall = data.get("overall_status", "unknown")
            score = data.get("readiness_score", "?")
            counts = data.get("counts", {})
            _log(
                "WARN",
                f"[{label}] harness health: {overall.upper()} "
                f"(score={score}, "
                f"pass={counts.get('pass', 0)}, "
                f"warn={counts.get('warn', 0)}, "
                f"fail={counts.get('fail', 0)})",
            )
            # Surface individual failures
            for check in data.get("checks", []):
                if check.get("status") == "fail":
                    _log("ERR", f"[{label}]   FAIL {check['name']}: {check['message']}")
        except (json.JSONDecodeError, KeyError):
            _log("WARN", f"[{label}] health check exited {proc.returncode}; raw output: {raw[:300]}")
        result.unfixable.append(f"{label}: health check returned non-zero (rc={proc.returncode})")


# ── Orchestration ────────────────────────────────────────────────────────────

HEALERS: list[tuple[str, Callable[[HealResult, bool], None]]] = [
    ("Missing __init__.py", heal_missing_init_files),
    ("Broken symlinks", heal_broken_symlinks),
    ("Corrupted .beads state", heal_beads_state),
    ("Stale git index.lock", heal_git_index_lock),
    ("Missing .gitignore entries", heal_gitignore_entries),
    ("Orphaned .pyc files", heal_orphaned_pyc),
    ("Harness health check", heal_run_harness_health),
]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Chromatic Harness V2 — comprehensive self-healing script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="detect issues and report without applying any fixes (dry-run)",
    )
    parser.add_argument(
        "--healer",
        metavar="NAME",
        help="run only the named healer (partial match, case-insensitive)",
    )
    args = parser.parse_args()

    mode = "CHECK-ONLY" if args.check_only else "AUTO-HEAL"
    print(bold(f"\n[auto_heal] Chromatic Harness V2 — {mode}"))
    print(f"  repo   : {REPO}")
    print(f"  log    : {LOG_FILE}")
    print(f"  started: {_ts()}\n")

    result = HealResult()
    healers = HEALERS

    if args.healer:
        key = args.healer.lower()
        healers = [(name, fn) for name, fn in HEALERS if key in name.lower()]
        if not healers:
            print(red(f"  No healer matched '{args.healer}'"))
            print(f"  Available: {', '.join(n for n, _ in HEALERS)}")
            return 1

    for name, fn in healers:
        print(bold(f"[{name}]"))
        try:
            fn(result, args.check_only)
        except Exception as exc:
            _log("ERR", f"Unhandled exception in healer '{name}': {exc}")
            result.unfixable.append(f"{name}: unhandled exception — {exc}")
        print()

    # ── Summary ───────────────────────────────────────────────────────────────
    print(bold("── Summary ──────────────────────────────────────────────────"))
    if result.fixed:
        print(green(f"  Fixed    ({len(result.fixed)}):"))
        for item in result.fixed:
            print(green(f"    + {item}"))
    if result.skipped:
        print(yellow(f"  Skipped  ({len(result.skipped)}) [check-only]:"))
        for item in result.skipped:
            print(yellow(f"    ~ {item}"))
    if result.unfixable:
        print(red(f"  Unfixable({len(result.unfixable)}):"))
        for item in result.unfixable:
            print(red(f"    x {item}"))
    if result.clean:
        print(f"  Clean    ({len(result.clean)}): {', '.join(result.clean)}")

    print()
    if result.unfixable:
        print(red(bold("  RESULT: FAIL — unfixable issues remain (see log)")))
        _log("ERR", f"run complete — unfixable: {result.unfixable}")
    elif result.skipped:
        print(yellow(bold("  RESULT: ISSUES DETECTED (check-only mode — no changes made)")))
        _log("WARN", f"check-only run complete — skipped fixes: {result.skipped}")
    else:
        print(green(bold("  RESULT: OK — harness is clean")))
        _log("INFO", "run complete — all clean")

    _flush_log()
    return 0 if result.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
