#!/usr/bin/env python3
"""
doc_consolidator.py — Reduce .md sprawl in the Chromatic Harness V2.

Strategy:
  1. Find all .md files recursively.
  2. Group by filename.
  3. For identical-content groups: delete duplicates, keep canonical path.
  4. For differing groups: keep all but write pointer stubs at non-canonical paths.
  5. Archive completed-milestone root docs.
  6. Handle OBSERVABILITY_*.md: keep most-recent only, archive others.
  7. Log everything to 07_LOGS_AND_AUDIT/doc_consolidation.log.

Usage:
  python doc_consolidator.py --dry-run          # report only (default)
  python doc_consolidator.py --apply            # execute changes
  python doc_consolidator.py --apply --archive-to <path>
"""

import argparse
import hashlib
import logging
import os
import re
import shutil
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

# ── colour helpers ────────────────────────────────────────────────────────────
RESET = "\033[0m"
RED = "\033[31m"
GREEN = "\033[32m"
YELLOW = "\033[33m"
CYAN = "\033[36m"
BOLD = "\033[1m"

def _c(col: str, text: str) -> str:
    return f"{col}{text}{RESET}"

def header(msg: str) -> None:
    print(_c(BOLD + CYAN, f"\n{'='*60}"))
    print(_c(BOLD + CYAN, f"  {msg}"))
    print(_c(BOLD + CYAN, f"{'='*60}"))

def info(msg: str) -> None:
    print(_c(CYAN, f"  [INFO]  {msg}"))

def ok(msg: str) -> None:
    print(_c(GREEN, f"  [OK]    {msg}"))

def warn(msg: str) -> None:
    print(_c(YELLOW, f"  [WARN]  {msg}"))

def act(msg: str) -> None:
    print(_c(GREEN, f"  [ACT]   {msg}"))

def dry(msg: str) -> None:
    print(_c(YELLOW, f"  [DRY]   {msg}"))

def err(msg: str) -> None:
    print(_c(RED, f"  [ERR]   {msg}"))

# ── constants ─────────────────────────────────────────────────────────────────
HARNESS_ROOT = Path(__file__).resolve().parent.parent

# Files at repo root that should be archived (completed-milestone docs)
MILESTONE_DOCS = {
    "HARNESS_V2_30DAY_REMEDIATION_COMPLETE.md",
    "OPTION_C_COMPLETE.md",
}

# Canonical path rules per filename
# Maps filename → lambda(list[Path]) → canonical_path
CANONICAL_RULES: dict[str, str] = {
    "README.md": "root",            # repo root preferred
    "DEPLOYMENT_GUIDE.md": "root",  # repo root preferred
    "ARCHITECTURE.md": "02_DOCS",   # 02_DOCS/ preferred, else root
}

LOG_DIR = HARNESS_ROOT / "07_LOGS_AND_AUDIT"
LOG_FILE = LOG_DIR / "doc_consolidation.log"

# ── utilities ─────────────────────────────────────────────────────────────────

def sha256(path: Path) -> str:
    h = hashlib.sha256()
    try:
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
    except OSError:
        return ""
    return h.hexdigest()


def make_stub(source: Path, canonical: Path) -> str:
    rel = os.path.relpath(canonical, source.parent).replace("\\", "/")
    return (
        f"<!-- AUTO-GENERATED STUB — DO NOT EDIT -->\n"
        f"# {source.stem}\n\n"
        f"This document has been consolidated. The canonical copy is at:\n\n"
        f"[{canonical.name}]({rel})\n\n"
        f"_Generated by doc_consolidator.py on {datetime.utcnow().date()}_\n"
    )


def pick_canonical(paths: list[Path], rule: str | None) -> Path:
    """Select canonical path from a list according to rule."""
    root = HARNESS_ROOT

    if rule == "root":
        # prefer path directly in HARNESS_ROOT
        root_copies = [p for p in paths if p.parent == root]
        if root_copies:
            return root_copies[0]
        # fallback: shortest path
        return min(paths, key=lambda p: len(p.parts))

    if rule == "02_DOCS":
        doc_copies = [p for p in paths if "02_DOCS" in p.parts]
        if doc_copies:
            return min(doc_copies, key=lambda p: len(p.parts))
        root_copies = [p for p in paths if p.parent == root]
        if root_copies:
            return root_copies[0]
        return min(paths, key=lambda p: len(p.parts))

    # default: shortest relative path from harness root
    return min(paths, key=lambda p: len(p.relative_to(root).parts))


def setup_logging(dry_run: bool) -> logging.Logger:
    logger = logging.getLogger("doc_consolidator")
    logger.setLevel(logging.DEBUG)
    if not LOG_DIR.exists():
        LOG_DIR.mkdir(parents=True, exist_ok=True)
    fh = logging.FileHandler(LOG_FILE, encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fmt = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
    fh.setFormatter(fmt)
    logger.addHandler(fh)
    mode = "DRY-RUN" if dry_run else "APPLY"
    logger.info(f"=== doc_consolidator started ({mode}) ===")
    return logger


# ── core logic ────────────────────────────────────────────────────────────────

def collect_md_files() -> list[Path]:
    files = []
    for p in HARNESS_ROOT.rglob("*.md"):
        # skip .git internals
        if ".git" in p.parts:
            continue
        files.append(p)
    return files


def group_by_name(files: list[Path]) -> dict[str, list[Path]]:
    groups: dict[str, list[Path]] = defaultdict(list)
    for f in files:
        groups[f.name].append(f)
    return dict(groups)


def handle_observability(
    files: list[Path],
    archive_to: Path,
    dry_run: bool,
    logger: logging.Logger,
) -> dict:
    """For OBSERVABILITY_*.md: keep the most recent, archive the rest."""
    # Separate dated reports from persistent docs
    report_pat = re.compile(r"OBSERVABILITY_REPORT_\d{4}-\d{2}-\d{2}\.md", re.IGNORECASE)
    reports = [f for f in files if report_pat.match(f.name)]
    persistent = [f for f in files if not report_pat.match(f.name)]

    stats = {"archived": 0, "kept": 0}

    # For reports: group by name, keep most-recent, archive older duplicates
    report_groups: dict[str, list[Path]] = defaultdict(list)
    for r in reports:
        report_groups[r.name].append(r)

    for name, copies in report_groups.items():
        if len(copies) == 1:
            stats["kept"] += 1
            continue
        # sort by mtime desc, keep newest
        copies_sorted = sorted(copies, key=lambda p: p.stat().st_mtime, reverse=True)
        canonical = copies_sorted[0]
        stats["kept"] += 1
        for dup in copies_sorted[1:]:
            dest = archive_to / "observability-old" / dup.name
            if dry_run:
                dry(f"Would archive old OBSERVABILITY report: {dup.relative_to(HARNESS_ROOT)}")
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(dup), str(dest))
                logger.info(f"ARCHIVED OBSERVABILITY report {dup} → {dest}")
                act(f"Archived old report: {dup.relative_to(HARNESS_ROOT)}")
            stats["archived"] += 1

    # For persistent OBSERVABILITY docs: keep as-is (unique names expected)
    for p in persistent:
        stats["kept"] += 1

    return stats


def consolidate(
    groups: dict[str, list[Path]],
    archive_to: Path,
    dry_run: bool,
    logger: logging.Logger,
) -> dict:
    stats = {
        "total_before": sum(len(v) for v in groups.values()),
        "deleted": 0,
        "stubs_created": 0,
        "archived": 0,
        "kept": 0,
        "obs_archived": 0,
    }

    # Collect all OBSERVABILITY_*.md files across all groups
    obs_files: list[Path] = []
    for name, paths in groups.items():
        if name.upper().startswith("OBSERVABILITY_"):
            obs_files.extend(paths)

    # Handle observability separately
    if obs_files:
        header("Handling OBSERVABILITY_*.md files")
        obs_stats = handle_observability(obs_files, archive_to, dry_run, logger)
        stats["obs_archived"] += obs_stats["archived"]
        stats["kept"] += obs_stats["kept"]

    # Archive completed-milestone root docs
    header("Archiving completed-milestone docs")
    for milestone_name in MILESTONE_DOCS:
        src = HARNESS_ROOT / milestone_name
        if src.exists():
            dest = archive_to / milestone_name
            if dry_run:
                dry(f"Would archive milestone doc: {milestone_name}")
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(src), str(dest))
                logger.info(f"ARCHIVED milestone {src} → {dest}")
                act(f"Archived milestone: {milestone_name}")
            stats["archived"] += 1

    # Process each filename group
    header("Processing duplicate filename groups")
    for name, paths in sorted(groups.items()):
        # Skip if it's an OBSERVABILITY file (already handled)
        if name.upper().startswith("OBSERVABILITY_"):
            continue
        # Skip if only one copy
        if len(paths) == 1:
            stats["kept"] += 1
            continue

        rule = CANONICAL_RULES.get(name)
        canonical = pick_canonical(paths, rule)
        duplicates = [p for p in paths if p != canonical]

        # Compute hashes
        canon_hash = sha256(canonical)
        identical: list[Path] = []
        different: list[Path] = []
        for dup in duplicates:
            if sha256(dup) == canon_hash and canon_hash:
                identical.append(dup)
            else:
                different.append(dup)

        # Delete identical duplicates
        for dup in identical:
            rel = dup.relative_to(HARNESS_ROOT)
            if dry_run:
                dry(f"Would delete identical copy: {rel}")
            else:
                dup.unlink()
                logger.info(f"DELETED identical {dup} (canonical: {canonical})")
                act(f"Deleted identical: {rel}")
            stats["deleted"] += 1

        # Write stubs for differing copies
        for dup in different:
            rel = dup.relative_to(HARNESS_ROOT)
            stub_content = make_stub(dup, canonical)
            if dry_run:
                dry(f"Would replace differing copy with stub: {rel}")
            else:
                with open(dup, "w", encoding="utf-8") as f:
                    f.write(stub_content)
                logger.info(f"STUB written {dup} → points to {canonical}")
                act(f"Stub created: {rel}")
            stats["stubs_created"] += 1

        stats["kept"] += 1  # canonical kept

    return stats


def print_summary(stats: dict, archive_to: Path, dry_run: bool) -> None:
    mode = "DRY-RUN" if dry_run else "APPLIED"
    header(f"Consolidation Summary [{mode}]")
    info(f"Archive destination : {archive_to}")
    info(f"Total .md before    : {stats['total_before']}")
    info(f"Milestone docs archived: {stats['archived']}")
    info(f"OBSERVABILITY archived : {stats['obs_archived']}")
    ok(f"Identical dupes deleted: {stats['deleted']}")
    ok(f"Differing → stubs      : {stats['stubs_created']}")
    info(f"Canonical copies kept  : {stats['kept']}")
    removed = stats["deleted"] + stats["archived"] + stats["obs_archived"]
    stubbed = stats["stubs_created"]
    total_after_est = stats["total_before"] - removed
    info(f"Estimated .md after    : {total_after_est}  (stubs counted as kept)")
    if dry_run:
        warn("No files were modified — re-run with --apply to execute.")
    else:
        ok("All changes applied.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Consolidate .md files in Chromatic Harness V2")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", dest="dry_run", action="store_true",
                      default=True, help="Report only, no changes (default)")
    mode.add_argument("--apply", dest="dry_run", action="store_false",
                      help="Execute the consolidation")
    parser.add_argument("--archive-to", dest="archive_to", default=None,
                        help="Directory for archived docs (default: 12_HANDOFFS/archive/doc-consolidation-YYYY-MM-DD)")
    args = parser.parse_args()

    dry_run: bool = args.dry_run

    # Resolve archive destination
    if args.archive_to:
        archive_to = Path(args.archive_to)
    else:
        date_str = datetime.utcnow().strftime("%Y-%m-%d")
        archive_to = HARNESS_ROOT / "12_HANDOFFS" / "archive" / f"doc-consolidation-{date_str}"

    logger = setup_logging(dry_run)

    header(f"doc_consolidator — {'DRY RUN' if dry_run else 'APPLY MODE'}")
    info(f"Harness root : {HARNESS_ROOT}")
    info(f"Archive to   : {archive_to}")
    info(f"Log file     : {LOG_FILE}")

    # Collect files
    info("Scanning for .md files…")
    all_md = collect_md_files()
    info(f"Found {len(all_md)} .md files")

    # Ensure archive dir exists (only if applying)
    if not dry_run:
        archive_to.mkdir(parents=True, exist_ok=True)

    groups = group_by_name(all_md)
    dup_groups = {k: v for k, v in groups.items() if len(v) > 1}
    info(f"Unique filenames     : {len(groups)}")
    info(f"Filenames with dupes : {len(dup_groups)}")

    stats = consolidate(groups, archive_to, dry_run, logger)
    print_summary(stats, archive_to, dry_run)

    logger.info(
        f"=== Run complete: deleted={stats['deleted']} stubs={stats['stubs_created']} "
        f"archived={stats['archived']} obs_archived={stats['obs_archived']} ==="
    )


if __name__ == "__main__":
    main()
