#!/usr/bin/env python3
"""generate_command_matrix.py — single-source-of-truth doc generator (j5ik / gh-109).

Renders docs/governance/CLAUDE_COMMAND_MATRIX.md deterministically from
config/claude_command_registry.yaml so the human-facing command matrix can never
drift from the governed registry. Follow-on from PR #103 / gh-99.

Modes:
    (default)   regenerate the matrix file on disk
    --check     render in memory and compare to the on-disk file; exit 1 on drift
                (this is the CI/pre-push-safe mode — no mutation)

Always writes a fail-open artifact to 07_LOGS_AND_AUDIT/command_matrix/latest.json
per the artifact+summarize() gate contract.

Dependency-light: PyYAML if available, clear SystemExit otherwise.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "config" / "claude_command_registry.yaml"
MATRIX_PATH = ROOT / "docs" / "governance" / "CLAUDE_COMMAND_MATRIX.md"
ARTIFACT_PATH = ROOT / "07_LOGS_AND_AUDIT" / "command_matrix" / "latest.json"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_command_matrix.py — DO NOT EDIT BY HAND. -->\n"
    "<!-- Regenerate: python scripts/generate_command_matrix.py  ·  Drift check: --check -->"
)

# How each registry `mutation` value is shown in the "Mutates State?" column.
_MUTATION_DISPLAY = {
    "conditional": "Conditional",
    "none": "No",
    "none_by_default": "No (by default)",
    "inspect_by_default": "Inspect by default",
    "yes": "Yes",
}


def load_registry(path: Path | None = None) -> dict[str, Any]:
    p = path or REGISTRY_PATH
    try:
        import yaml  # type: ignore
    except Exception as exc:  # noqa: BLE001
        raise SystemExit(f"PyYAML is required to read {p}: {exc}") from exc
    return yaml.safe_load(p.read_text(encoding="utf-8")) or {}


def _cell(value: str) -> str:
    """Escape a pipe so it cannot break the Markdown table."""
    return value.replace("|", "\\|")


def _script_cell(cmd: dict[str, Any]) -> str:
    parts: list[str] = []
    for key in ("script", "fallback_script"):
        val = cmd.get(key)
        if val:
            parts.append(f"`{val}`")
    return " / ".join(parts) if parts else "—"


def render_matrix(registry: dict[str, Any]) -> str:
    """Render the full Markdown matrix from the registry (deterministic)."""
    commands = registry.get("commands", [])
    lines: list[str] = [
        GENERATED_BANNER,
        "",
        "# Claude Command Matrix",
        "",
        "Generated from `config/claude_command_registry.yaml`. Every governed Claude",
        "slash command is an **adapter only** — authority lives in the harness scripts",
        "and gates listed below, never in the command itself.",
        "",
        "| Command | Purpose | Authority Source | Script / Fallback | Mutates State? | Required Gates | Status |",
        "|---|---|---|---|---|---|---|",
    ]
    for cmd in commands:
        name = cmd.get("name", "?")
        purpose = cmd.get("purpose", "").rstrip(".")
        authority = cmd.get("authority_source", "—")
        script = _script_cell(cmd)
        mutation = _MUTATION_DISPLAY.get(cmd.get("mutation", ""), cmd.get("mutation", "—"))
        gates = ", ".join(cmd.get("required_gates", []) or []) or "—"
        status = "Allowed" if cmd.get("allowed", False) else "Forbidden"
        row = (
            f"| `{_cell(name)}` | {_cell(purpose)} | `{_cell(str(authority))}` "
            f"| {script} | {_cell(mutation)} | {_cell(gates)} | {status} |"
        )
        lines.append(row)

    lines += [
        "",
        "## Forbidden Logic Guardrails",
        "",
        "Each command declares logic it may **never** implement (enforced by",
        "`scripts/validate_claude_adapter_policy.py` against `claude_adapter_rules.yaml`).",
        "",
        "| Command | Forbidden Logic |",
        "|---|---|",
    ]
    for cmd in commands:
        name = cmd.get("name", "?")
        forbidden = ", ".join(cmd.get("forbidden_logic", []) or []) or "—"
        lines.append(f"| `{_cell(name)}` | {_cell(forbidden)} |")

    lines.append("")
    return "\n".join(lines)


def write_matrix(registry: dict[str, Any] | None = None, path: Path | None = None) -> str:
    reg = registry if registry is not None else load_registry()
    content = render_matrix(reg)
    target = path or MATRIX_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return content


def check_matrix(registry: dict[str, Any] | None = None, path: Path | None = None) -> bool:
    """Return True if the on-disk matrix matches the rendered output (no drift)."""
    reg = registry if registry is not None else load_registry()
    target = path or MATRIX_PATH
    expected = render_matrix(reg)
    actual = target.read_text(encoding="utf-8") if target.is_file() else ""
    return expected == actual


def summarize(registry_path: Path | None = None, matrix_path: Path | None = None) -> dict[str, Any]:
    """Fail-open rollup + artifact write per the gate contract."""
    try:
        reg = load_registry(registry_path)
        in_sync = check_matrix(reg, matrix_path)
        result = {
            "status": "ok",
            "command_count": len(reg.get("commands", [])),
            "in_sync": in_sync,
        }
    except Exception as exc:  # noqa: BLE001
        result = {"status": "error", "error": str(exc), "command_count": None, "in_sync": None}
    try:
        ARTIFACT_PATH.parent.mkdir(parents=True, exist_ok=True)
        ARTIFACT_PATH.write_text(json.dumps(result, indent=2), encoding="utf-8")
    except Exception:  # noqa: BLE001
        pass
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the Claude command matrix from the registry (j5ik)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the on-disk matrix matches the registry; exit 1 on drift (no mutation).",
    )
    args = parser.parse_args()

    if args.check:
        ok = check_matrix()
        summarize()
        if ok:
            print("PASS: CLAUDE_COMMAND_MATRIX.md is in sync with the registry")
            return 0
        print("FAIL: CLAUDE_COMMAND_MATRIX.md is out of date.")
        print("  Run: python scripts/generate_command_matrix.py")
        return 1

    write_matrix()
    summarize()
    print(f"WROTE: {MATRIX_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
