#!/usr/bin/env python3
"""Generate the console theme module from the asset-swap packs.

Reads every ``assets/prompt_variants/*.asset_pack.yaml`` (the visual source of
truth), validates each against ``schemas/asset_swap_pack.schema.json``, normalises
each pack's *heterogeneous* colour keys into one canonical ``ConsoleTheme`` token
set, and emits a typed TS module the Next.js console imports directly.

Why a generator (not runtime YAML parsing): the console has no YAML dependency
(``package.json`` ships only next/react). Generating a checked-in ``.ts`` keeps the
YAML packs canonical, validates them against the registered schema, and adds zero
frontend runtime dependencies. Adding/altering a theme = edit the YAML + re-run this.

Run:  python scripts/generate_console_themes.py
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml
from jsonschema import Draft202012Validator

ROOT = Path(__file__).resolve().parents[1]
PACK_DIR = ROOT / "assets" / "prompt_variants"
SCHEMA = ROOT / "schemas" / "asset_swap_pack.schema.json"
OUT = ROOT / "05_FRONTEND_CONSOLE" / "src" / "lib" / "themes.generated.ts"

DEFAULT_THEME_ID = "default_neon"

# Shared dark structural neutrals. Asset packs vary their *brand* palettes (and
# may override the app background), but the panel/text scaffolding stays dark so
# every theme remains a legible operations console.
BASE = {
    "bg": "#0a0a0a",
    "panelBg": "#111111",
    "panelBorder": "#333333",
    "heading": "#888888",
    "text": "#e0e0e0",
    "muted": "#555555",
}

# Fallbacks when a pack omits a semantic colour entirely.
SEMANTIC_FALLBACK = {
    "success": "#22c55e",
    "warning": "#f59e0b",
    "danger": "#ef4444",
    "info": "#3b82f6",
}


def _first(colors: dict[str, str]) -> str:
    return next(iter(colors.values()), "#3b82f6")


def _pick(colors: dict[str, str], *keys: str, default: str) -> str:
    for k in keys:
        if k in colors and colors[k]:
            return colors[k]
    return default


def normalise(pack: dict) -> dict:
    """Map an asset pack's idiosyncratic palette to canonical UI tokens."""
    colors: dict[str, str] = dict(pack.get("colors", {}))
    first = _first(colors)
    accent = _pick(colors, "primary", "runtime", "quasar", "cmp", "prism", default=first)
    brand = _pick(colors, "secondary", "cmp", "prism", "magnets", default=accent)
    return {
        "id": pack["asset_pack_id"],
        "name": pack.get("name", pack["asset_pack_id"]),
        "style": pack.get("style", ""),
        "bg": _pick(colors, "deep_space", "bg", default=BASE["bg"]),
        "panelBg": BASE["panelBg"],
        "panelBorder": BASE["panelBorder"],
        "heading": BASE["heading"],
        "text": BASE["text"],
        "muted": BASE["muted"],
        "accent": accent,
        "brand": brand,
        "success": _pick(colors, "success", "mcp", default=SEMANTIC_FALLBACK["success"]),
        "warning": _pick(colors, "warning", "magnets", default=SEMANTIC_FALLBACK["warning"]),
        "danger": _pick(colors, "danger", "risk", "plasma", default=SEMANTIC_FALLBACK["danger"]),
        "info": _pick(colors, "info", "quasar", "runtime", default=accent),
        "palette": colors,
        "components": dict(pack.get("components", {})),
    }


def main() -> None:
    validator = Draft202012Validator(json.loads(SCHEMA.read_text(encoding="utf-8")))
    packs = sorted(PACK_DIR.glob("*.asset_pack.yaml"))
    if not packs:
        raise SystemExit(f"No asset packs found in {PACK_DIR}")

    themes: list[dict] = []
    errors: list[str] = []
    for path in packs:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        schema_errors = sorted(validator.iter_errors(data), key=lambda e: e.path)
        if schema_errors:
            errors.append(f"{path.name}: " + "; ".join(e.message for e in schema_errors))
            continue
        themes.append(normalise(data))

    if errors:
        raise SystemExit("Asset pack schema validation failed:\n  " + "\n  ".join(errors))

    ids = [t["id"] for t in themes]
    default_id = DEFAULT_THEME_ID if DEFAULT_THEME_ID in ids else ids[0]

    body = json.dumps(themes, indent=2)
    union = " | ".join(f'"{i}"' for i in ids)
    ts = f"""// AUTO-GENERATED by scripts/generate_console_themes.py — DO NOT EDIT BY HAND.
// Source of truth: assets/prompt_variants/*.asset_pack.yaml
// (validated against schemas/asset_swap_pack.schema.json). Regenerate after editing a pack:
//   python scripts/generate_console_themes.py

export interface ConsoleTheme {{
  id: string;
  name: string;
  style: string;
  bg: string;
  panelBg: string;
  panelBorder: string;
  heading: string;
  text: string;
  muted: string;
  accent: string;
  brand: string;
  success: string;
  warning: string;
  danger: string;
  info: string;
  palette: Record<string, string>;
  components: Record<string, string>;
}}

export type ThemeId = {union};

export const THEMES: ConsoleTheme[] = {body};

export const DEFAULT_THEME_ID: ThemeId = "{default_id}";

export function getTheme(id: string | null | undefined): ConsoleTheme {{
  return THEMES.find((t) => t.id === id) ?? THEMES.find((t) => t.id === DEFAULT_THEME_ID) ?? THEMES[0];
}}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(ts, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} with {len(themes)} themes: {', '.join(ids)}")


if __name__ == "__main__":
    main()
