#!/usr/bin/env python3
"""Usage-calibration dashboard (P4).

Renders 05_REPORTS/USAGE_CALIBRATION_DASHBOARD.md from the calibration
artifacts: current windows + forecast, cap-calibration trend, epoch timeline,
and weekly/monthly rollup. Markdown + Mermaid xychart-beta, matching
generate_dashboard.py. Read-only over the artifacts; run after calibrate+rollup.
"""
from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import usage_calibration_lib as L

_REPORT = L.HARNESS / "05_REPORTS" / "USAGE_CALIBRATION_DASHBOARD.md"
WINDOW_LABELS = {"five_hour": "5-hour", "seven_day": "weekly"}


def _m(wtok):
    """Weighted tokens -> millions, 1 decimal (for compact charts/tables)."""
    try:
        return round(float(wtok) / 1_000_000, 1)
    except (TypeError, ValueError):
        return 0.0


def _fmt_wtok(wtok):
    if wtok is None:
        return "—"
    n = float(wtok)
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    if n >= 1_000:
        return f"{round(n / 1000)}k"
    return str(int(n))


def _current_windows_table(caps):
    rows = ["| Window | Used | Cap | Confidence | Forecast |",
            "|--------|------|-----|-----------|----------|"]
    for key, label in WINDOW_LABELS.items():
        c = (caps.get(key) or {}) if isinstance(caps, dict) else {}
        used = _fmt_wtok(c.get("used_wtok"))
        cap = _fmt_wtok(c.get("cap_wtok"))
        conf = c.get("confidence", "none")
        fc = c.get("forecast") or {}
        if fc.get("time_to_cap_hr") is not None:
            verdict = "⚠ before reset" if fc.get("verdict") == "cap_before_reset" else "ok"
            forecast = f"{fc['time_to_cap_hr']}h to cap ({verdict})"
        else:
            forecast = "—"
        rows.append(f"| {label} | {used} | {cap} | {conf} | {forecast} |")
    return "\n".join(rows)


def _cap_trend_chart(window, label):
    """xychart of calibrated cap (millions wtok) across firm history runs."""
    series = []
    for h in L.iter_jsonl(L.CALIBRATION_HISTORY):
        w = h.get(window) or {}
        if w.get("cap_wtok") and w.get("confidence") in ("ok", "prov"):
            series.append(_m(w["cap_wtok"]))
    series = series[-30:]
    if len(series) < 2:
        return f"_Not enough firm calibration history for {label} yet (collecting)._"
    xs = ", ".join(str(i + 1) for i in range(len(series)))
    ys = ", ".join(str(v) for v in series)
    top = max(series) * 1.2 or 1
    return (f"```mermaid\nxychart-beta\n    title \"{label} cap estimate (M wtok)\"\n"
            f"    x-axis [{xs}]\n    y-axis \"M wtok\" 0 --> {round(top, 1)}\n"
            f"    line [{ys}]\n```")


def _weekly_trend_chart(rollup):
    weekly = rollup.get("weekly", {}) if isinstance(rollup, dict) else {}
    items = list(weekly.items())[-12:]
    if len(items) < 1:
        return "_No weekly rollup yet._"
    labels = ", ".join(f'"{k[5:10]}"' for k, _ in items)  # MM-DD of the anchor
    vals = ", ".join(str(_m(b["wtok"])) for _, b in items)
    top = max((_m(b["wtok"]) for _, b in items), default=1) * 1.2 or 1
    return (f"```mermaid\nxychart-beta\n    title \"Weekly usage (M wtok, Tue-1pm-ET weeks)\"\n"
            f"    x-axis [{labels}]\n    y-axis \"M wtok\" 0 --> {round(top, 1)}\n"
            f"    bar [{vals}]\n```")


def _epoch_timeline(epochs):
    eps = epochs.get("epochs", []) if isinstance(epochs, dict) else []
    if not eps:
        return "_No epochs recorded yet._"
    rows = ["| Epoch | Opened | Reason |", "|-------|--------|--------|"]
    for e in eps:
        cur = " ◀ current" if e["id"] == epochs.get("current") else ""
        rows.append(f"| {e['id']}{cur} | {e.get('opened_at', '—')[:19]} | {e.get('reason', '')} |")
    return "\n".join(rows)


def _monthly_table(rollup):
    monthly = rollup.get("monthly", {}) if isinstance(rollup, dict) else {}
    if not monthly:
        return "_No monthly rollup yet._"
    rows = ["| Month | Usage | Events |", "|-------|-------|--------|"]
    for k, b in sorted(monthly.items()):
        rows.append(f"| {k} | {_fmt_wtok(b['wtok'])} | {b['events']} |")
    return "\n".join(rows)


def build_dashboard():
    caps = L.read_json(L.CALIBRATED_CAPS)
    epochs = L.read_json(L.EPOCHS)
    rollup = L.read_json(L.ROLLUP)
    updated = caps.get("updated_at", "—") if isinstance(caps, dict) else "—"
    epoch_id = caps.get("epoch_id", "—") if isinstance(caps, dict) else "—"
    wver = caps.get("weight_table_version", "—") if isinstance(caps, dict) else "—"

    return f"""# Usage Calibration Dashboard

> Auto-generated by `python scripts/usage_dashboard.py`
> Updated: {updated} · Epoch: {epoch_id} · Weights: {wver}
> Caps derived from logged usage vs Anthropic's native rate-limit % (snapshot-delta).
> Unit: weighted tokens (wtok), sonnet-input = 1.0.

## Current Windows

{_current_windows_table(caps)}

## 5-hour Cap Calibration Trend

{_cap_trend_chart("five_hour", "5-hour")}

## Weekly Cap Calibration Trend

{_cap_trend_chart("seven_day", "weekly")}

## Weekly Usage (rollup)

{_weekly_trend_chart(rollup)}

## Monthly Usage

{_monthly_table(rollup)}

## Epoch Timeline

{_epoch_timeline(epochs)}

---
- Provisional caps (small sample) are hidden from the statusline used/cap until "ok".
- A new epoch opens when a firm cap shifts >40% for 3 consecutive runs (limit change).
- xychart-beta requires GitHub Mermaid v10+ to render.
"""


def main():
    _REPORT.parent.mkdir(parents=True, exist_ok=True)
    _REPORT.write_text(build_dashboard(), encoding="utf-8")
    print(f"dashboard: wrote {_REPORT.relative_to(L.HARNESS)}")


if __name__ == "__main__":
    main()
